SOURCES_KVDB = \
		./KvDB/VarTextField.cpp \
		./KvDB/BinaryField.cpp \
		./KvDB/VarIntField.cpp \
		./KvDB/DataFeature.cpp \
		./KvDB/VarBinaryField.cpp \
		./KvDB/dev_buffer.cpp \
		./KvDB/TextType.cpp \
		./KvDB/DoubleField.cpp \
		./KvDB/TextField.cpp \
		./KvDB/FDNumberType.cpp \
		./KvDB/test_smdtable.cpp \
		./KvDB/FieldType.cpp \
		./KvDB/TableDef.cpp \
		./KvDB/FieldTypeFactory.cpp \
		./KvDB/stdafx.cpp \
		./KvDB/FLDoubleField.cpp \
		./KvDB/SMDValue.cpp \
		./KvDB/FloatField.cpp \
		./KvDB/SMDTableSegment.cpp \
		./KvDB/GeometryQuery.cpp \
		./KvDB/SMDStream.cpp \
		./KvDB/IntegerField.cpp \
		./KvDB/SMDSStorage.cpp \
		./KvDB/LongField.cpp \
		./KvDB/SMDPageManagement.cpp \
		./KvDB/SMDPageFile.cpp \
		./KvDB/NumberType.cpp \
		./KvDB/SMDPage.cpp \
		./KvDB/Record.cpp \
		./KvDB/SMDMetaSegment.cpp \
		./KvDB/ShortField.cpp \
		./KvDB/SMDMemStream.cpp \
		./KvDB/SMDDataSegment.cpp \
		./KvDB/SMDIndexSegment.cpp \
		./KvDB/SMDFileStream.cpp