SOURCES_KVDB = \
		./KvDB/VarTextField.cc \
		./KvDB/BinaryField.cc \
		./KvDB/VarIntField.cc \
		./KvDB/DataFeature.cc \
		./KvDB/VarBinaryField.cc \
		./KvDB/dev_buffer.cc \
		./KvDB/TextType.cc \
		./KvDB/DoubleField.cc \
		./KvDB/TextField.cc \
		./KvDB/FDNumberType.cc \
		./KvDB/test_smdtable.cc \
		./KvDB/FieldType.cc \
		./KvDB/TableDef.cc \
		./KvDB/FieldTypeFactory.cc \
		./KvDB/stdafx.cc \
		./KvDB/FLDoubleField.cc \
		./KvDB/SMDValue.cc \
		./KvDB/FloatField.cc \
		./KvDB/SMDTableSegment.cc \
		./KvDB/GeometryQuery.cc \
		./KvDB/SMDStream.cc \
		./KvDB/IntegerField.cc \
		./KvDB/SMDSStorage.cc \
		./KvDB/LongField.cc \
		./KvDB/SMDPageManagement.cc \
		./KvDB/SMDPageFile.cc \
		./KvDB/NumberType.cc \
		./KvDB/SMDPage.cc \
		./KvDB/Record.cc \
		./KvDB/SMDMetaSegment.cc \
		./KvDB/ShortField.cc \
		./KvDB/SMDMemStream.cc \
		./KvDB/SMDDataSegment.cc \
		./KvDB/SMDIndexSegment.cc \
		./KvDB/SMDFileStream.cc